"""comfyui_wxa8_quantizer -- standalone ComfyUI-native checkpoint quantizer.

This package is the modular source of the single-file converter artifact
``comfyui_wxa8_quantizer.py`` (regenerated by ``tools/build_single_file.py``).
The package and the artifact share one implementation and produce identical
outputs.
"""

from __future__ import annotations

from comfyui_wxa8_quantizer._version import __version__
from comfyui_wxa8_quantizer.constants import (
    CONVERTER_NAME,
    CONVERTER_VERSION,
    DEFAULT_W4A4_LINEAR_DTYPE,
    FORMAT_INT8,
    FORMAT_MIXED,
    FORMAT_ORIGINAL,
    FORMAT_W4A4,
    FORMAT_W4A8,
    MIXED_FORMATS,
    get_converter_version,
    set_converter_version,
)
from comfyui_wxa8_quantizer.cli import build_arg_parser, main
from comfyui_wxa8_quantizer.errors import (
    CalibrationError,
    CompressionGateError,
    InputError,
    OutputError,
    PickleInputError,
    PolicyError,
    QualityGateError,
    QuantizerError,
    RuntimeCompatibilityError,
    SelfTestFailure,
    UnknownArchitectureError,
    UnsupportedArchitectureError,
    UsageError,
    ValidationError,
)
from comfyui_wxa8_quantizer.selftests import run_self_tests

__all__ = [
    "__version__",
    "CONVERTER_NAME",
    "CONVERTER_VERSION",
    "FORMAT_W4A8",
    "FORMAT_W4A4",
    "FORMAT_INT8",
    "FORMAT_MIXED",
    "FORMAT_ORIGINAL",
    "MIXED_FORMATS",
    "DEFAULT_W4A4_LINEAR_DTYPE",
    "get_converter_version",
    "set_converter_version",
    "build_arg_parser",
    "main",
    "run_self_tests",
    "QuantizerError",
    "UsageError",
    "InputError",
    "PickleInputError",
    "UnknownArchitectureError",
    "UnsupportedArchitectureError",
    "PolicyError",
    "QualityGateError",
    "CompressionGateError",
    "RuntimeCompatibilityError",
    "CalibrationError",
    "ValidationError",
    "OutputError",
    "SelfTestFailure",
]
